name: Latest tech talks workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-tech-talks:
    name: Update this repo's README with latest tech talks posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLp6PZvmMwlKsL0yPBfEKb2CrKWfNYtdIm"
          comment_tag_name: "TECH-TALKS"
